#!/bin/bash
# install-git-hooks.sh — install Synapse pre-commit + commit-msg hooks
#
# Idempotent. Wires:
#   pre-commit:
#     - scripts/check_claude_md_edit.py    (CLAUDE.md 5-dim fact check)
#     - scripts/frontmatter_lint.py --strict-staged
#                                          (block new/modified obs/*.md w/o frontmatter)
#   commit-msg:
#     - scripts/check_decision_log.py "$1" (D-NNN archive enforcement, correct timing)
#
# Run once per clone/checkout. Safe to re-run.

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PRE_COMMIT_HOOK="$REPO_ROOT/.git/hooks/pre-commit"
COMMIT_MSG_HOOK="$REPO_ROOT/.git/hooks/commit-msg"

if [ ! -d "$REPO_ROOT/.git" ]; then
  echo "ERROR: not a git repo: $REPO_ROOT" >&2
  exit 1
fi

# ── pre-commit hook ─────────────────────────────────────────────────────
cat > "$PRE_COMMIT_HOOK" << 'HOOK_EOF'
#!/bin/bash
# Synapse-Mini pre-commit hook (auto-generated by scripts/install-git-hooks.sh)
#
# Enforces (at staging time, before commit message is written):
#   1. CLAUDE.md edit checklist (5 dimensions) — only if CLAUDE.md staged
#   2. frontmatter strict on staged obs/*.md (new/modified files only)
#
# Note: decision-log enforcement runs in the commit-msg hook, not here,
# because pre-commit fires before the commit message is reliably available.
#
# Bypass (emergency only): git commit --no-verify
# Lysander must log any --no-verify to decision-log within 24h.

set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# Resolve a python interpreter that actually runs (not just resolves on PATH).
PY=""
for cand in python python3 py; do
  if "$cand" -c "import sys" >/dev/null 2>&1; then
    PY="$cand"
    break
  fi
done
if [ -z "$PY" ]; then
  echo "[pre-commit] ERROR: no working python interpreter (tried python/python3/py)"
  exit 1
fi

export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

# Check 1: CLAUDE.md fact-check (only if CLAUDE.md is staged)
if git diff --cached --name-only | grep -qx 'CLAUDE.md'; then
  echo "[pre-commit] CLAUDE.md modified, running fact-check..."
  if ! "$PY" scripts/check_claude_md_edit.py; then
    echo ""
    echo "[pre-commit] CLAUDE.md fact-check FAILED. Commit blocked."
    echo "[pre-commit] Fix the listed issues, or use --no-verify in emergencies."
    exit 1
  fi
fi

# Check 2: frontmatter strict on staged obs/*.md
if [ -f scripts/frontmatter_lint.py ]; then
  if ! "$PY" scripts/frontmatter_lint.py --strict-staged; then
    echo ""
    echo "[pre-commit] frontmatter check FAILED for staged obs/*.md."
    echo "[pre-commit] Add 12-field frontmatter or remove from stage."
    exit 1
  fi
fi

echo "[pre-commit] All checks passed."
HOOK_EOF

chmod +x "$PRE_COMMIT_HOOK"

# ── commit-msg hook ─────────────────────────────────────────────────────
cat > "$COMMIT_MSG_HOOK" << 'HOOK_EOF'
#!/bin/bash
# Synapse-Mini commit-msg hook (auto-generated by scripts/install-git-hooks.sh)
#
# Enforces:
#   - decision-log archive presence for L3+ commits (D-YYYY-MMDD-NNN reference,
#     decision-log/* file modification, or 'no-decision' opt-out)
#
# Triggered by `git commit` AFTER the user enters the message.
# Argument: $1 = path to .git/COMMIT_EDITMSG (set natively by git).

set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

PY=""
for cand in python python3 py; do
  if "$cand" -c "import sys" >/dev/null 2>&1; then
    PY="$cand"
    break
  fi
done
if [ -z "$PY" ]; then
  echo "[commit-msg] ERROR: no working python interpreter"
  exit 1
fi

export PYTHONUTF8=1
export PYTHONIOENCODING=utf-8

if ! "$PY" scripts/check_decision_log.py "$1"; then
  echo ""
  echo "[commit-msg] decision-log check FAILED. Commit blocked."
  echo "[commit-msg] Add D-YYYY-MMDD-NNN to message, modify a decision-log/* file,"
  echo "             or include 'no-decision' in commit message if not a decision."
  exit 1
fi

echo "[commit-msg] decision-log check passed."
HOOK_EOF

chmod +x "$COMMIT_MSG_HOOK"

echo "[install-git-hooks] hooks installed:"
echo "  pre-commit  : $PRE_COMMIT_HOOK"
echo "  commit-msg  : $COMMIT_MSG_HOOK"
echo "[install-git-hooks] active checks:"
echo "  pre-commit  : CLAUDE.md fact-check + frontmatter strict-staged"
echo "  commit-msg  : decision-log enforcement"
